<?php

/**
 * @file
 * Contains dp_mistake.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dp_mistake_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dp_mistake module.
    case 'help.page.dp_mistake':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Informing editors about mistakes') . '</p>';
      return $output;

    default:
  }
}

function dp_mistake_page_attachments(array &$attachments) {

  // Unconditionally attach an asset to the page.
  $attachments['#attached']['library'][] = 'dp_mistake/main';

//  // Conditionally attach an asset to the page.
//  if (!\Drupal::currentUser()
//    ->hasPermission('may pet kittens')) {
//    $attachments['#attached']['library'][] = 'core/jquery';
//  }
}

function dp_mistake_preprocess_html(&$variables) {
  $variables['#attached']['drupalSettings']['dp_mistake']['color'] = 'green';
}