# Schema for the configuration files of the SI Statistics module.

si_stat.settings:
  type: config_object
  label: 'SI Statistics settings'
  mapping:
    enabled_entity_types:
      label: Enabled entity types
      type: sequence
      sequence:
        type: string
    display_max_age:
      type: integer
      label: 'How long any statistics may be cached, i.e. the refresh interval'
